Description: >

    This template deploys a VPC, with a pair of public and private subnets spread 
    across two Availabilty Zones. It deploys an Internet Gateway, with a default 
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ), 
    and default routes for them in the private subnets.

    It then deploys a highly available ECS cluster using an AutoScaling Group, with 
    ECS hosts distributed across multiple Availability Zones. 

    Finally, it deploys a pair of example ECS services from containers published in 
    Amazon EC2 Container Registry (Amazon ECR).

    Last Modified: 22nd September 2016
    Author: Paul Maddox <pmaddox@amazon.com>

Parameters:
    VPC:
        Description: VPC Id like 'vpc-18ac277d'.
        Type: AWS::EC2::VPC::Id
        
    Subnets:
        Description: Choose which subnets this ECS cluster should be deployed to
        Type: String
        
    KeyName:
        Description: KeyName
        Type: AWS::EC2::KeyPair::KeyName

    RootCACrt:
        Description: ROOT CA Certificate
        Type: String

    ProxyHost:
        Description: Proxy host.
        Type: String
        
    ProxyPort:
        Description: Proxy port.
        Type: Number
        
    GitLabURL:
        Description: GitLab URL
        Type: String

    RunnerRegistrationToken:
        Description: Runner registration token
        Type: String

    RunnerConcurrent:
        Description: Runner Concurrent
        Type: Number

    RunnerCheckInterval:
        Description: Runner check interval
        Type: Number

    RunnerEnvironment:
        Description: Runner environment
        Type: String

    RunnerDNS:
        Description: Runner dns
        Type: String

    RunnerExtraHosts:
        Description: Runner extra_hosts
        Type: String

    RunnerPrivileged:
        Description: Runner privileged
        Type: String
        Default: false

    RunnerPullPolicy:
        Description: Runner pull_policy
        Type: String
        Default: if-not-present

Resources:

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: infrastructure/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPC

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: infrastructure/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !Ref VPC
                Subnets: !Ref Subnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: infrastructure/ecs-cluster.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                InstanceType: t2.micro
                ClusterSize: 1
                VPC: !Ref VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !Ref Subnets
                KeyName: !Ref KeyName
                RootCACrt: !Ref RootCACrt
                ProxyHost: !Ref ProxyHost
                ProxyPort: !Ref ProxyPort
                GitLabURL: !Ref GitLabURL
                RunnerRegistrationToken: !Ref RunnerRegistrationToken
                RunnerConcurrent: !Ref RunnerConcurrent
                RunnerCheckInterval: !Ref RunnerCheckInterval
                RunnerEnvironment: !Ref RunnerEnvironment
                RunnerDNS: !Ref RunnerDNS
                RunnerExtraHosts: !Ref RunnerExtraHosts
                RunnerPrivileged: !Ref RunnerPrivileged
                RunnerPullPolicy: !Ref RunnerPullPolicy

Outputs:

    ProductServiceUrl: 
        Description: The URL endpoint for the product service
        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "products" ]]

    WebsiteServiceUrl: 
        Description: The URL endpoint for the website service
        Value: !Join ["", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "/" ]]
